# 混合端口 (mixed-port)
# 同时监听 HTTP 和 SOCKS5 协议的端口。
# 例如: 7890
mixed-port: 7890

# 允许局域网连接 (allow-lan)
# 设置为 true 后，局域网内的其他设备可以连接到此代理。
# 默认值为 false。
allow-lan: true

# 代理模式 (mode)
# - rule: 规则模式，根据规则进行分流。
# - global: 全局模式，所有流量都走代理。
# - direct: 直连模式，所有流量都不走代理。
mode: rule

# 日志级别 (log-level)
# - info: 显示普通信息。
# - warning: 显示警告信息。
# - error: 显示错误信息。
# - debug: 显示用于调试的详细信息。
# - silent: 不输出任何日志。
log-level: info

# 外部控制器 (external-controller)
# RESTful API 的监听地址，用于与其他程序或脚本进行交互。
external-controller: '127.0.0.1:9090'

# 外部 UI (external-ui)
# 用于托管 Web UI 界面的目录路径。
# 例如: 'path/to/your/ui/folder'
# external-ui: 'dashboard'

# API 密钥 (secret)
# 为 RESTful API 设置密码，增强安全性。
# secret: 'your-secret-password'

proxies:
  # Shadowsocks (SS) 示例
  - name: "SS-节点"
    type: ss
    server: your-server-address
    port: your-server-port
    cipher: aes-256-gcm
    password: "your-password"
    udp: true # 开启 UDP 转发

  # VMess 示例
  - name: "VMess-节点"
    type: vmess
    server: your-server-address
    port: your-server-port
    uuid: "your-uuid"
    alterId: 0
    cipher: auto
    tls: true # 开启 TLS
    network: "ws" # 使用 WebSocket 传输
    ws-opts:
      path: "/your-path"
      headers:
        Host: your-host.com

proxy-groups:
  # 手动选择 (select)
  # 可以在 UI 界面或通过 API 手动选择使用的节点。
  - name: "手动选择"
    type: select
    proxies:
      - "SS-节点"
      - "VMess-节点"

  # 自动测速 (url-test)
  # 自动选择延迟最低的节点。
  - name: "自动选择"
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300 # 测速间隔 (秒)
    proxies:
      - "SS-节点"
      - "VMess-节点"

  # 故障转移 (fallback)
  # 当主节点不可用时，自动切换到备用节点。
  - name: "故障转移"
    type: fallback
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
      - "SS-节点"
      - "VMess-节点"

rules:
  # 直连局域网和私有地址
  - 'DOMAIN-SUFFIX,local,DIRECT'
  - 'IP-CIDR,127.0.0.0/8,DIRECT'
  - 'IP-CIDR,172.16.0.0/12,DIRECT'
  - 'IP-CIDR,192.168.0.0/16,DIRECT'
  - 'IP-CIDR,10.0.0.0/8,DIRECT'

  # 屏蔽广告
  - 'DOMAIN-KEYWORD,ad,REJECT'

  # 直连中国大陆常见域名
  - 'GEOIP,CN,DIRECT'
  - 'DOMAIN-SUFFIX,cn,DIRECT'

  # 其他流量走代理
  - 'MATCH,手动选择'